### ISSUE TITLE
コルネキーボードではtwpair_on_jis.cが正しく動作しない

### ISSUE THREAD

**Issue by tor-nky** [eswai/qmk_firmware#13]
### Issue Description

「’」（アポストロフィ）を何度か押した後にシフトが入りっぱなしになるなどという現象が、なぜかコルネキーボード限定で起きます。

users/naginata_v15/twpair_on_jis.c の60-61行目を
```
  bool lshifted = get_mods() & MOD_BIT(KC_LSFT); // シフトキーの状態
  bool rshifted = get_mods() & MOD_BIT(KC_RSFT);
```
と書きかえると、原因はわからないものの直りました。

**Comment by eswai** [comment]
ありがとうございます。マージしました。
