### ISSUE TITLE
Linuxで句読点や編集モード入力がうまくいかない

### ISSUE THREAD

**Issue by tor-nky** [eswai/qmk_firmware#14]
Linuxでユニコード入力がうまくいかなくて、_qmk_firmware/keyboards/.../keymaps/naginata_v15/config.h_ に
```
#define USB_POLLING_INTERVAL_MS 8   // sets the USB polling rate in milliseconds ←毎秒125レポートの意
#define TAP_CODE_DELAY 24   // Sets the delay between `register_code` and `unregister_code` ←上の数値の倍数にする
```
を追加したらできるようになりました。
環境によってはさらに数値の調整がいるかもしれません。

テスト環境：Debian 11.7.0 amd64

**Comment by eswai** [comment]
Ubuntuでも再現できました。ありがとうございます。

**Comment by tor-nky** [comment]
キー出力が遅くなってしまうのが欠点ですよね。

_qmk_firmware/quantum/unicode/unicode.c_ 内の _send_nibble_wrapper()_
を書き換えて、Linuxのときだけウェイトを入れる方法でもいけるかもしれません。

顔文字をユニコード入力するキーマップを見ることから、ほかにも実例がないか調べてみます。

**Comment by eswai** [comment]
この設定はMacのunicode入力でも有効な気がします。
karabiner-elementsとの併用でMacでもunicode入力ができるようになったのですが、この設定をしておかないと取りこぼしたりしますね。

**Comment by tor-nky** [comment]
Macもまだ何かありそうなんですね。
なので、下のは備忘録です。

---
Linuxのユニコードの問題だけだったら次のようにすれば充分だとわかりました。
1. LCTL(LSFT(KC_U)) の後、10msないし8ms空ける。
1. ユニコードを16進数で入力するときは、1キー出力するごとに32ms空ける。
1. ユニコード1文字ごとにスペースを出力し、24ms空ける。
(続けてユニコードを入力するときは 1. から再び出力する)

 _qmk_firmware/quantum/unicode/unicode.c_ 内の関数を2つ書き換えればできますし、USB_POLLING_INTERVAL_MS、TAP_CODE_DELAY の設定は不要です。

**Comment by eswai** [comment]
UNICODE_TYPE_DELAYをおおきめ数字にしておくと安定しますね。

**Comment by tor-nky** [comment]
control+f19 でかなモードにするスクリプトは、
```"to":[{"key_code":"lang1","modifiers":["shift"]},{"key_code":"lang1"}]```
でいいと思います。
再変換にならないように「shift+かな」「かな」の2打にするのがポイントです。

もっとも、QMKから ```tap_code(KC_LANGUAGE_1);``` だけでいいかもしれませんが。

**Comment by eswai** [comment]
ありがとうございます。修正しました。

**Comment by tor-nky** [comment]
Linuxではユニコード以外の、例えば "？{改行}" が入力に失敗する問題もあるんですね。
Linuxでどうしても使いたい人だけ調整すればいいんじゃないかと思います。
