### ISSUE TITLE
[Bug] Macで未確定文字が残っている時にUNICODE入力すると未確定文字の前に入力される

### ISSUE THREAD

**Issue by eswai** [eswai/qmk_firmware#15]
### Describe the Bug

Macで未確定文字が残っている時にUNICODE入力すると未確定文字の前に入力される。
未確定文字を確定してからUNICODE入力に移りたいが、未確定文字がなくても副作用のない確定操作がわからない。

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by tor-nky** [comment]
未確定文字が残っているとき（特に変換窓がでているとき）は、「Unicode 16進数入力」に切り替えられるだけではいけないのは知りませんでした。
↓ そういえば私も前に困っていたようです。
https://github.com/tor-nky/KE-complex_modifications-NAGINATA/issues/3

未確定文字を確定させるのは簡単です。
* まず、キーボード設定（設定→キーボード→テキスト入力/入力ソース→編集）に「英語/U.S.」を登録し、キーボードの英数キーを押したら「英語/U.S.」になるようにします。
* あとは「Unicode 16進数入力」にする前に「英数キー」を出力するだけです。

おそらく英数キーを押して日本語以外になればいいのだと思います。

この方法は Benkei からもらいました。
https://github.com/eswai/Benkei/issues/11
https://github.com/eswai/Benkei/blame/main/Benkei/AppDelegate.m の関数 sendUnicode() 1736行目

便利なので、薙刀式のKarabiner-Elements版や BLE QMK版に使わせていただいています。

----
_qmk_firmware/users/naginata_v15/naginata_v15.c_ の 445行目を
```tap_code(KC_LANGUAGE_2);  // (Mac)英数```
に入れ替え

**Comment by tor-nky** [comment]
ちなみにその後の
```
      register_code(KC_LCTL); // Unicode HEX Inputへ切り替え
      tap_code(KC_F20);
      unregister_code(KC_LCTL);
```
を
```
      tap_code16(C(KC_F20));
```
などとするとバイナリの節約になります。（1個あたり6バイト）

**Comment by tor-nky** [comment]
> * 「Unicode 16進数入力」にする前に「英数キー」を出力するだけです。

Karabiner-Elements のスクリプトに足してもいいかもしれません。

**Comment by eswai** [comment]
ありがとうございます。うまくいきました。
Benkeiでやっていたとは完全に忘れていました。

**Comment by eswai** [comment]
クローズします
