### ISSUE TITLE
[Bug] NICOLAからのRAISEレイヤーでRAISE押下側キーボードの挙動が不安定

### ISSUE THREAD

**Issue by Yifumi** [eswai/qmk_firmware#8]
こんにちは。

cherry corneに書き込んで、ありがたく使わせて頂いております。ご提供に大変感謝しております。
当方、自作キーボードとQMKは初めてなので、的外れでしたら、どうぞご容赦下さい。

書き込み、使用環境は、M1 Mac Mini、 macOS Big Sur 11.2.1 です。

タイトルの通りですが、気づいたのはNICOLA時に方向キーで移動しようとしたときです（右側でRAISE押下してUPなど押下）。
数回に一度は矢印キーが入りますが、あとはNICOLAのキー入力になります（UPなら、く）。
ご提供いただいているまま、手を加えずに使っております。

QWERTYレイヤーでは問題無く動作します。

左側（LOWERキーがあるほう）の空いている場所に、UPとDOWNを書いて見ましたが、この場合は、NICOLAから問題なく動きます。

RAISEとLOWERのマップだけを入れ替えてみましたが（RAISE、LOWERキーはそのまま）、やはり右側だけうまく動作しません（テンキーなどがうまく動かず、矢印キーなどは安定動作）。

私の環境のせいかもしれませんが、もし解決策をお持ちなら助けて頂きたいと思い、
不適切かも知れませんが、BUG報告の場所に書き込ませて頂きました。

以上、よろしくお願いします。

**Comment by eswai** [comment]
報告ありがとうございます。nicola、nicola2、nicola3の３つのキーマップがありますが、どれをお使いでしょうか。

**Comment by Yifumi** [comment]
あまりのレスポンスの速さに驚いてしまいました。
お忙しいところ、ありがとうございます。

qmk_firmware/keyboards/crkbd/keymaps/nicola2/

のものを使わせて頂いております。

以上です。

**Comment by Yifumi** [comment]
nicola2以外のキーマップの存在を知らなかったので、いまnicola3で試してみました。
ご報告した不具合の部分しか確かめていませんが、ご報告した問題は起きません。
取り急ぎご報告致します。

以上です。

**Comment by eswai** [comment]
ありがとうございます。nicola3はでない、nicola2だと頻度は低いですが発生することを確認しました。
nicola3(原作 https://github.com/sadaoikebe)のほうがNICOLA規格に準拠しているので、問題がなければ3をおすすめいたします。

**Comment by Yifumi** [comment]
eswai 様

早速のご対応ありがとうございました。
nicola3を使わせて頂きたいと思います。

迅速にご対応いただき、大変助かりました。
ありがとうございました。

以上、失礼致します。

**Comment by eswai** [comment]
他にも問題あったので、nicola2、nicola3のコードを最新のQMK対応に更新しました。nicola2でも上記問題は解消された気がします。nicola3のほうがおすすめです。
- QMKの標準の分割キーボードコード、OLEDコードを使用する
- 最新のQMKでコンパイルエラーがでるのを解消

**Comment by Yifumi** [comment]
eswai 様

ご対応ありがとうございます。

新しいnicola3を試しましたところ、前verのようにmakeでwarningは出ませんでした。
しかし、親指に配置されている、CTLSPCとCMDENTが効かなくなっているようです。

ご確認頂けますでしょうか。

以上です。

**Comment by Yifumi** [comment]
すみません。新しいコンパイルコマンドでやっていません。
すぐに確認します。

**Comment by Yifumi** [comment]
make crkbd/rev1/common:nicola2:flash
make crkbd/rev1/common:nicola3:flash

ともに、Errorが出て通りませんでした。

./qmk_firmwareに./crkbdがないので、

make keyboards/crkbd/rev1/common:nicola3:flash

としてみましたが、駄目なようです。
ご提示頂いたmakeコマンドの意味を把握できていず大変恐縮ですが、よろしくお願いします。

以上です。

**Comment by eswai** [comment]
このリポジトリをgit pullして、コンパイルしてエラーになるという理解で良いでしょうか。

**Comment by Yifumi** [comment]
恥ずかしながら、git pullコマンドを知らず、
nicola3ディレクトリより、手作業で自分のディレクトリにコピーしていました。

とり急ぎ、git pullについて調べます。

**Comment by eswai** [comment]
とりあえずバイナリをおいておきます。qmk toolboxで書き込めるはずです。

[crkbd_rev1_common_nicola.zip](https://github.com/eswai/qmk_firmware/files/6095149/crkbd_rev1_common_nicola.zip)

**Comment by Yifumi** [comment]
makeでwrningが出る段階でのnicola3をバックアップしておいたので、ひとまずは使用できる状態を確保しています。
自作キーボードを紹介したブログに書いてあるコマンドをコピーしてqmk環境を構築して、
eswai様のkeymaps/nicola2（もしくはnicola3）の中のファイルを手作業でコピーしてはmakeしていたので、
gitによる連携を前提にしているeswai様のご対応について行けなくなったのだと理解しております。

おそらくですが、git cloneでeswai様のqmk_firmwareと連携して作業する必要があるということですよね。
この理解で勉強しつつ進めてみます。未熟者がご迷惑をお掛けします。

**Comment by Yifumi** [comment]
eswai様

お世話になっております。

eswai/qmk_firmwareのクローンを作成し、qmk_firmwareフォルダにてutil/qmk_install.shを実行し、
make crkbd:nicola3を実行したところ、makeはできましたが、
make crkbd:nicola3:avrdudeで書き込んでも、CTRSPCのスペース、CMDENTのエンターがききません。

そこで、make crkbd/rev1/common:nicola3:flash を実行しましたが、

ERROR: Bootloader not found. Trying again in 5s.

で止まります。

もはや基本的すぎてeswai様に質問する内容ではないかと思いますが、
参照すべきHPだけでも教えて頂けないでしょうか。

以上、よろしくお願いします。

**Comment by eswai** [comment]
https://github.com/eswai/qmk_firmware/blob/master/keyboards/crkbd/keymaps/nicola3/rules.mk
ここの1行目を削除したらいけないでしょうか。
QMKはかなり変化が速く、それにあわせていくと、過去との互換性がなくなりつらいところです。

**Comment by Yifumi** [comment]
ありがとうございます。

おっしゃる行のコメントアウトで（#BOOTLOADER = qmk-dfu）、
makeが通り、書き込むことができました。（コマンド:make crkbd/rev1/common:nicola3:flash）

しかし、CTRSPC（左側右端）のスペース、CMDENT（右側左端）のエンターが効かないという症状はそのままです。

以上です。

**Comment by eswai** [comment]
ではconfig.hの以下の設定の数字を大きくしてみましょうか。これでゆっくり押しても大丈夫だとおもうのですが。
'''#define TAPPING_TERM 300'''

**Comment by Yifumi** [comment]
eswai様

そういうことだったんですね。もとの設定でも、意識して早く押したらいけました。
僕はキーをがっつり下げっぱなしにするタイプだったんですね。

お陰様で万事解決と思います。
昼間から今まで、長い時間、最後までお付き合い頂きありがとうございました。
こんな素人相手で、さぞかし、もどかしい思いをされたと思います。
お陰さまで、楽しいネイティブ親指シフトキーボードライフが送れそうです。

心より感謝申し上げます。

以上、失礼致します。

**Comment by eswai** [comment]
無事に動いて何よりです。
